# Data Cleaning

### Project Objective

The objective of this task is to demonstrate professional data cleaning skills by transforming a deliberately messy customer sales dataset into a clean, consistent, and analysis-ready dataset.

### Dataset

The dataset contains customer information, demographic attributes, income, purchase information, membership status, and payment method.

### Data Cleaning Operations

The following operations will be performed:

- Initial data inspection
- Data quality assessment
- Missing value analysis and treatment
- Duplicate detection and removal
- Categorical data standardisation
- Date format standardisation
- Numeric data type correction
- Outlier detection using the IQR method
- Outlier treatment
- Final validation
- Before vs. after comparison
- Export of the cleaned dataset

## 1. Import Required Libraries

The following Python libraries are used:

- **Pandas** – data loading, manipulation, cleaning, and analysis
- **NumPy** – numerical operations and missing-value handling
- **Matplotlib** – visualization of outliers and distributions

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:.2f}".format)

## 2. Load the Dataset

The original dataset is intentionally messy and contains missing values, duplicate records, inconsistent categorical formatting, mixed date formats, incorrect data types, and numerical anomalies.

The original dataset will be preserved throughout the cleaning process so that the results can be compared before and after cleaning.

In [2]:
file_path = "../dataset/Messy_Customer_Sales.csv"

df = pd.read_csv(file_path)

df.head()

,Customer_ID,Customer_Name,Gender,Age,City,Annual_Income,Purchase_Amount,Purchase_Date,Membership_Status,Payment_Method
0,CUST1019,Sneha Mishra,Female,59.00,DELHI,35949.0,657.15,2025-02-24,No,UPI
1,CUST1043,Pooja Sinha,Male,25.00,Kanpur,43284.0,11541.9,2025-05-07,Yes,UPI
2,CUST1037,Vikram Joshi,Female,52.00,Agra,46964.0,8468.17,2025-04-19,Yes,Cash
3,CUST1077,Rahul Yadav,Male,NaN,Delhi,79115.0,5935.62,2025-08-17,No,UPI
4,CUST1054,Vikram Joshi,Male,23.00,Delhi,59124.0,5926.93,2025-06-09,No,Credit Card

In [3]:
df_original = df.copy()

print("Dataset loaded successfully.")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully.
Rows: 125
Columns: 10

## 3. Initial Dataset Inspection

Before cleaning the dataset, its structure, dimensions, data types, missing values, duplicate records, and sample records are inspected.

This establishes the initial data quality baseline.

In [4]:
print("Dataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nFirst 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

Dataset Shape:
(125, 10)

Column Names:
['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'City', 'Annual_Income', 'Purchase_Amount', 'Purchase_Date', 'Membership_Status', 'Payment_Method']

Data Types:
Customer_ID              str
Customer_Name            str
Gender                   str
Age                  float64
City                     str
Annual_Income            str
Purchase_Amount          str
Purchase_Date            str
Membership_Status        str
Payment_Method           str
dtype: object

First 5 Rows:

,Customer_ID,Customer_Name,Gender,Age,City,Annual_Income,Purchase_Amount,Purchase_Date,Membership_Status,Payment_Method
0,CUST1019,Sneha Mishra,Female,59.00,DELHI,35949.0,657.15,2025-02-24,No,UPI
1,CUST1043,Pooja Sinha,Male,25.00,Kanpur,43284.0,11541.9,2025-05-07,Yes,UPI
2,CUST1037,Vikram Joshi,Female,52.00,Agra,46964.0,8468.17,2025-04-19,Yes,Cash
3,CUST1077,Rahul Yadav,Male,NaN,Delhi,79115.0,5935.62,2025-08-17,No,UPI
4,CUST1054,Vikram Joshi,Male,23.00,Delhi,59124.0,5926.93,2025-06-09,No,Credit Card

Last 5 Rows:

,Customer_ID,Customer_Name,Gender,Age,City,Annual_Income,Purchase_Amount,Purchase_Date,Membership_Status,Payment_Method
120,CUST1107,Nikhil Das,Female,38.00,Agra,112745.0,5623.61,2025-11-15,No,Credit Card
121,CUST1015,Sneha Mishra,Female,52.00,Lucknow,58251.0,12483.63,2025-02-12,Yes,NaN
122,CUST1093,Kavya Agarwal,Female,53.00,Delhi,116027.0,10588.36,2025-10-04,Yes,Credit Card
123,CUST1052,Rahul Yadav,Male,36.00,Kanpur,108781.0,₹7800,2025-06-03,Yes,Debit Card
124,CUST1103,Isha Tiwari,Male,55.00,Agra,95953.0,NaN,2025-11-03,No,Cash

### Statistical Overview

In [5]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Customer_ID,125,120,CUST1082,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer_Name,123,15,Pooja Sinha,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,120,7,Male,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,121.00,NaN,NaN,NaN,41.48,16.41,-5.00,29.00,42.00,53.00,150.00
City,120,10,Agra,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Annual_Income,121,116,89275.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Purchase_Amount,122,117,676.24,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Purchase_Date,121,118,2025-02-15,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Membership_Status,125,6,Yes,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Payment_Method,123,7,UPI,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 4. Data Quality Report

A data quality report is generated to identify the main issues before cleaning.

The report includes:

- Null values per column
- Null percentage
- Number of unique values
- Data type
- Duplicate row count
- Minimum and maximum values for numerical columns

These checks help determine which cleaning operations are required.

In [6]:
quality_report = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Null_Count": df.isnull().sum().values,
    "Null_Percentage": (df.isnull().mean() * 100).round(2).values,
    "Unique_Values": df.nunique(dropna=True).values
})

quality_report

              Column Data_Type  Null_Count  Null_Percentage  Unique_Values
0        Customer_ID       str           0             0.00            120
1      Customer_Name       str           2             1.60             15
2             Gender       str           5             4.00              7
3                Age   float64           4             3.20             40
4               City       str           5             4.00             10
5      Annual_Income       str           4             3.20            116
6    Purchase_Amount       str           3             2.40            117
7      Purchase_Date       str           4             3.20            118
8  Membership_Status       str           0             0.00              6
9     Payment_Method       str           2             1.60              7

### Duplicate Report

In [8]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 3

### Numerical Range Anomaly Check

Numerical columns are inspected for unrealistic minimum and maximum values.

For this dataset, age should represent a realistic customer age, annual income should be positive and reasonable, and purchase amount should not contain negative values.

In [10]:
numeric_columns = ["Age", "Annual_Income", "Purchase_Amount"]

range_report = pd.DataFrame({
    "Column": numeric_columns,
    "Current_Dtype": [df[col].dtype for col in numeric_columns],
    "Missing_Count": [df[col].isna().sum() for col in numeric_columns]
})

range_report

            Column Current_Dtype  Missing_Count
0              Age       float64              4
1    Annual_Income           str              4
2  Purchase_Amount           str              3

## 5. Data Type Issues

The initial inspection shows that some columns that should be numerical or datetime values are stored as objects because the original dataset contains currency symbols, spaces, and mixed date formats.

The following target data types will be used:

| Column | Target Type | Reason |
|---|---|---|
| Customer_ID | string | Identifier, not a numerical measure |
| Customer_Name | string | Text field |
| Gender | string | Categorical field |
| Age | integer | Customer age |
| City | string | Categorical field |
| Annual_Income | float | Monetary numerical value |
| Purchase_Amount | float | Monetary numerical value |
| Purchase_Date | datetime | Date-based analysis |
| Membership_Status | string | Categorical field |
| Payment_Method | string | Categorical field |

## 6. Missing Data Analysis and Treatment Strategy

Missing values are handled according to the meaning and data type of each column.

### Strategy

- **Age:** Median imputation is used because age is numerical and the median is less affected by extreme values.
- **Annual_Income:** Median imputation is used because income can be skewed and may contain extreme values.
- **Purchase_Amount:** Median imputation is used because purchase amounts can also be skewed by unusually large purchases.
- **Gender:** Mode imputation is used because gender is categorical and the most frequent valid category provides a reasonable replacement.
- **City:** Mode imputation is used because city is categorical.
- **Purchase_Date:** Rows with missing purchase dates will be removed because a transaction without a date cannot be reliably assigned to a specific time period.
- **Payment_Method:** Mode imputation is used because it is a categorical variable.
- **Customer_Name:** Rows where the customer name is completely missing will be removed because the record lacks an important identifying field.
- **Membership_Status:** No missing values are currently present, so no imputation is required.
- **Customer_ID:** No missing values are currently present. IDs should not be statistically imputed.

### Missing Value Report

In [11]:
missing_report = pd.DataFrame({
    "Column": df.columns,
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().mean() * 100).round(2)
})

missing_report = missing_report.sort_values(
    "Missing_Count",
    ascending=False
)

missing_report

                              Column  Missing_Count  Missing_Percentage
City                            City              5                4.00
Gender                        Gender              5                4.00
Purchase_Date          Purchase_Date              4                3.20
Annual_Income          Annual_Income              4                3.20
Age                              Age              4                3.20
Purchase_Amount      Purchase_Amount              3                2.40
Payment_Method        Payment_Method              2                1.60
Customer_Name          Customer_Name              2                1.60
Customer_ID              Customer_ID              0                0.00
Membership_Status  Membership_Status              0                0.00

### Preserving Missing Counts

In [12]:
missing_before = df.isnull().sum().sum()
duplicates_before = df.duplicated().sum()
rows_before = len(df)

print("Total missing values:", missing_before)
print("Duplicate rows:", duplicates_before)
print("Rows:", rows_before)

Total missing values: 29
Duplicate rows: 3
Rows: 125

### Row Deletion Decision

Rows with a missing Customer_Name and Purchase_Date are removed because they lack sufficient identifying and transaction information.

Statistical imputation is inappropriate for these fields because creating a fictional customer identity or transaction date could introduce incorrect information into the dataset.

In [13]:
rows_to_delete = df["Customer_Name"].isna() & df["Purchase_Date"].isna()

print("Rows identified for deletion:", rows_to_delete.sum())

df = df[~rows_to_delete].copy()

print("Rows after deletion:", len(df))

Rows identified for deletion: 2
Rows after deletion: 123

## 7. Data Type Correction

Annual income and purchase amount contain values with currency symbols, spaces, and numeric values stored as strings.

Currency symbols and unnecessary whitespace are removed before converting the columns to numeric values.

In [14]:
df["Annual_Income"] = (
    df["Annual_Income"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df["Purchase_Amount"] = (
    df["Purchase_Amount"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df["Annual_Income"] = pd.to_numeric(df["Annual_Income"], errors="coerce")
df["Purchase_Amount"] = pd.to_numeric(df["Purchase_Amount"], errors="coerce")

### Date Standardisation

Purchase_Date contains multiple date formats such as:

- YYYY-MM-DD
- DD/MM/YYYY
- YYYY/MM/DD
- DD-MM-YYYY
- Month DD, YYYY

The values are converted into a single pandas datetime format. Invalid or missing dates are converted to NaT and will be handled appropriately.

In [16]:
df["Purchase_Date"] = pd.to_datetime(df["Purchase_Date"], format="%Y-%m-%d")

### Missing Data Rows

In [17]:
missing_date_rows = df["Purchase_Date"].isna().sum()

print("Rows with missing/invalid Purchase_Date:", missing_date_rows)

Rows with missing/invalid Purchase_Date: 6

In [18]:
df = df.dropna(subset=["Purchase_Date"]).copy()

print("Rows after removing missing dates:", len(df))

Rows after removing missing dates: 117

## 8. Categorical Data Standardisation

Categorical values are standardised so that the same category is represented consistently.

For Gender:

- Male
- male
- M

are converted to:

**Male**

Similarly:

- Female
- female
- FEMALE
- F

are converted to:

**Female**

Invalid values such as "Unknown" are treated as missing and subsequently replaced with the mode.

In [19]:
df["Gender"] = (
    df["Gender"]
    .astype("string")
    .str.strip()
    .str.lower()
)

gender_mapping = {
    "male": "Male",
    "m": "Male",
    "female": "Female",
    "f": "Female"
}

df["Gender"] = df["Gender"].map(gender_mapping)

### Standardise City

In [20]:
df["City"] = (
    df["City"]
    .astype("string")
    .str.strip()
    .str.title()
)

valid_cities = [
    "Kanpur",
    "Delhi",
    "Lucknow",
    "Noida",
    "Jaipur",
    "Agra"
]

df.loc[~df["City"].isin(valid_cities), "City"] = pd.NA

### Membership Status Standardisation

Membership values are standardised into two valid categories:

- Yes
- No

Values such as "yes", "NO", and "Y" are converted to the appropriate standard representation.

Invalid values such as "Maybe" are treated as missing because they do not represent a valid membership category.

In [21]:
df["Membership_Status"] = (
    df["Membership_Status"]
    .astype("string")
    .str.strip()
    .str.lower()
)

membership_mapping = {
    "yes": "Yes",
    "y": "Yes",
    "no": "No",
    "n": "No"
}

df["Membership_Status"] = df["Membership_Status"].map(membership_mapping)

### Payment Method

In [22]:
df["Payment_Method"] = (
    df["Payment_Method"]
    .astype("string")
    .str.strip()
    .str.lower()
)

payment_mapping = {
    "cash": "Cash",
    "upi": "UPI",
    "credit card": "Credit Card",
    "debit card": "Debit Card"
}

df["Payment_Method"] = df["Payment_Method"].map(payment_mapping)

### Missing Value Imputation

In [23]:
# Numerical columns – median imputation
df["Age"] = df["Age"].fillna(df["Age"].median())

df["Annual_Income"] = df["Annual_Income"].fillna(
    df["Annual_Income"].median()
)

df["Purchase_Amount"] = df["Purchase_Amount"].fillna(
    df["Purchase_Amount"].median()
)

# Categorical columns – mode imputation
categorical_columns = [
    "Gender",
    "City",
    "Membership_Status",
    "Payment_Method"
]

for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Missing values after imputation:")
print(df.isnull().sum())

Missing values after imputation:
Customer_ID          0
Customer_Name        0
Gender               0
Age                  0
City                 0
Annual_Income        0
Purchase_Amount      0
Purchase_Date        0
Membership_Status    0
Payment_Method       0
dtype: int64

## 9. Duplicate Detection and Removal

Exact duplicate rows can cause double-counting and distort statistical analysis.

Duplicate rows were identified using pandas' `duplicated()` method.

Because these records contain exactly the same information as another record, retaining them would not add analytical value. Therefore, exact duplicate rows are removed.

In [24]:
duplicates_found = df.duplicated().sum()

print("Duplicate rows before removal:", duplicates_found)

df = df.drop_duplicates().copy()

print("Duplicate rows after removal:", df.duplicated().sum())
print("Rows after duplicate removal:", len(df))

Duplicate rows before removal: 3
Duplicate rows after removal: 0
Rows after duplicate removal: 114

## 10. Outlier Detection Using the IQR Method

The Interquartile Range (IQR) method is used to identify potential outliers in numerical columns.

### Formula

IQR = Q3 - Q1

Lower Bound = Q1 - 1.5 × IQR

Upper Bound = Q3 + 1.5 × IQR

Values below the lower bound or above the upper bound are considered potential outliers.

Outliers are not automatically errors. Each numerical column is evaluated before deciding whether to remove, cap, or retain the observations.

### IQR Function

In [25]:
def detect_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = data[
        (data[column] < lower_bound) |
        (data[column] > upper_bound)
    ]
    
    return Q1, Q3, IQR, lower_bound, upper_bound, outliers

### Outlier Report

In [26]:
outlier_report = []

numeric_columns = [
    "Age",
    "Annual_Income",
    "Purchase_Amount"
]

for col in numeric_columns:
    Q1, Q3, IQR, lower, upper, outliers = detect_outliers_iqr(df, col)
    
    outlier_report.append({
        "Column": col,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower_Bound": lower,
        "Upper_Bound": upper,
        "Outlier_Count": len(outliers)
    })

outlier_report = pd.DataFrame(outlier_report)

outlier_report

,Column,Q1,Q3,IQR,Lower_Bound,Upper_Bound,Outlier_Count
0,Age,29.00,52.00,23.00,-5.50,86.50,1
1,Annual_Income,51030.75,98585.25,47554.50,-20301.00,169917.00,1
2,Purchase_Amount,4670.01,12263.97,7593.96,-6720.92,23654.90,1

### Inspecting Outliers

In [27]:
for col in numeric_columns:
    Q1, Q3, IQR, lower, upper, outliers = detect_outliers_iqr(df, col)
    
    print(f"\n{'='*50}")
    print(f"Column: {col}")
    print(f"Lower Bound: {lower:.2f}")
    print(f"Upper Bound: {upper:.2f}")
    print(f"Outlier Count: {len(outliers)}")
    
    if len(outliers) > 0:
        display(outliers[["Customer_ID", col]])

==================================================
Column: Age
Lower Bound: -5.50
Upper Bound: 86.50
Outlier Count: 1

   Customer_ID    Age
68    CUST1014 150.00

==================================================
Column: Annual_Income
Lower Bound: -20301.00
Upper Bound: 169917.00
Outlier Count: 1

   Customer_ID  Annual_Income
21    CUST1079     5000000.00

==================================================
Column: Purchase_Amount
Lower Bound: -6720.92
Upper Bound: 23654.90
Outlier Count: 1

   Customer_ID  Purchase_Amount
13    CUST1097        250000.00

### Logical Range Validation

Statistical outlier detection alone is not sufficient.

Some values can be identified as invalid based on domain logic:

- Customer age should be between 18 and 100.
- Annual income should be positive.
- Purchase amount should be greater than or equal to zero.

These logical rules are therefore applied in addition to IQR-based detection.

In [28]:
invalid_age = (df["Age"] < 18) | (df["Age"] > 100)
invalid_income = df["Annual_Income"] <= 0
invalid_purchase = df["Purchase_Amount"] < 0

print("Invalid age records:", invalid_age.sum())
print("Invalid income records:", invalid_income.sum())
print("Invalid purchase amount records:", invalid_purchase.sum())

Invalid age records: 2
Invalid income records: 0
Invalid purchase amount records: 1

## 11. Outlier Treatment Decision

Outliers are treated according to whether they represent possible data-entry errors or legitimate extreme observations.

### Age

Age values below 18 or above 100 are considered invalid for this customer dataset. These values are replaced with the median age because the extreme values are clearly inconsistent with the intended domain.

### Annual Income

Extremely high income values may represent legitimate high-income customers. However, the intentionally inserted extreme value is considered a data-entry anomaly in this exercise. It will be capped at the IQR upper bound rather than deleting the entire customer record.

### Purchase Amount

Negative purchase amounts are invalid because a purchase amount cannot be negative in this dataset. These values are replaced with the median purchase amount.

Extremely high but positive purchase amounts are treated as potential legitimate transactions and are retained unless they violate the defined business rules.

### Rationale

Capping is preferred for extreme income values because it preserves the customer record while reducing the influence of an extreme value. Invalid values are corrected using median-based treatment rather than unnecessarily deleting otherwise useful records.

### Fixing Invalid Ages

In [29]:
age_median = df["Age"].median()

df.loc[
    (df["Age"] < 18) | (df["Age"] > 100),
    "Age"
] = age_median

### Fixing Negative Purchase Amounts

In [30]:
purchase_median = df["Purchase_Amount"].median()

df.loc[
    df["Purchase_Amount"] < 0,
    "Purchase_Amount"
] = purchase_median

### Cap Extreme Income

In [31]:
Q1 = df["Annual_Income"].quantile(0.25)
Q3 = df["Annual_Income"].quantile(0.75)

IQR = Q3 - Q1

income_upper_bound = Q3 + 1.5 * IQR

df["Annual_Income"] = df["Annual_Income"].clip(
    upper=income_upper_bound
)

print("Income upper cap:", income_upper_bound)

Income upper cap: 169917.0

## 12. Final Data Type Correction & Verification

After cleaning, each column is explicitly converted to its intended data type.

This ensures that identifiers remain strings, numerical measures are numeric, and purchase dates are stored as pandas datetime values.

In [34]:
df["Customer_ID"] = df["Customer_ID"].astype("string")
df["Customer_Name"] = df["Customer_Name"].astype("string")
df["Gender"] = df["Gender"].astype("string")
df["Age"] = df["Age"].round().astype("int64")
df["City"] = df["City"].astype("string")
df["Annual_Income"] = df["Annual_Income"].astype("float64")
df["Purchase_Amount"] = df["Purchase_Amount"].astype("float64")
df["Purchase_Date"] = pd.to_datetime(df["Purchase_Date"])
df["Membership_Status"] = df["Membership_Status"].astype("string")
df["Payment_Method"] = df["Payment_Method"].astype("string")

In [35]:
df.dtypes

Customer_ID                  string
Customer_Name                string
Gender                       string
Age                           int64
City                         string
Annual_Income               float64
Purchase_Amount             float64
Purchase_Date        datetime64[us]
Membership_Status            string
Payment_Method               string
dtype: object

#### **Final Missing Values Check**

In [36]:
print("Missing values after cleaning:")
display(df.isnull().sum())

Missing values after cleaning:

Customer_ID          0
Customer_Name        0
Gender               0
Age                  0
City                 0
Annual_Income        0
Purchase_Amount      0
Purchase_Date        0
Membership_Status    0
Payment_Method       0
dtype: int64

#### **Final Duplicate Check**

In [38]:
print("Duplicate rows after cleaning:", df.duplicated().sum())

Duplicate rows after cleaning: 0

#### **Final Range Validation**

In [39]:
print("Age range:", df["Age"].min(), "to", df["Age"].max())
print("Income range:", df["Annual_Income"].min(), "to", df["Annual_Income"].max())
print("Purchase range:", df["Purchase_Amount"].min(), "to", df["Purchase_Amount"].max())

Age range: 21 to 60
Income range: 30412.0 to 169917.0
Purchase range: 657.15 to 250000.0

## 13. Before vs. After Cleaning Summary

The following table compares the dataset before and after cleaning.

The comparison includes:

- Row count
- Total missing values
- Duplicate rows
- Number of columns
- Data type accuracy

This provides a measurable summary of the impact of the cleaning process.

In [40]:
expected_dtypes = {
    "Customer_ID": "string",
    "Customer_Name": "string",
    "Gender": "string",
    "Age": "int64",
    "City": "string",
    "Annual_Income": "float64",
    "Purchase_Amount": "float64",
    "Purchase_Date": "datetime64[ns]",
    "Membership_Status": "string",
    "Payment_Method": "string"
}

before_dtype_accuracy = sum(
    str(df_original[col].dtype) == dtype
    for col, dtype in expected_dtypes.items()
)

after_dtype_accuracy = sum(
    str(df[col].dtype) == dtype
    for col, dtype in expected_dtypes.items()
)

comparison = pd.DataFrame({
    "Metric": [
        "Row Count",
        "Total Missing Values",
        "Duplicate Rows",
        "Columns",
        "Correct Data Types"
    ],
    "Before Cleaning": [
        len(df_original),
        df_original.isnull().sum().sum(),
        df_original.duplicated().sum(),
        df_original.shape[1],
        f"{before_dtype_accuracy}/{len(expected_dtypes)}"
    ],
    "After Cleaning": [
        len(df),
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        df.shape[1],
        f"{after_dtype_accuracy}/{len(expected_dtypes)}"
    ]
})

comparison

                 Metric Before Cleaning After Cleaning
0             Row Count             125            114
1  Total Missing Values              29              0
2        Duplicate Rows               3              0
3               Columns              10             10
4    Correct Data Types            0/10           9/10

## 14. Final Clean Dataset

The cleaned dataset is now ready for downstream analysis.

The final dataset contains:

- Consistent categorical values
- Correct numerical data types
- Standardized datetime values
- No duplicate rows
- Handled missing values
- Corrected invalid numerical values
- Treated extreme outliers

In [41]:
display(df.head(10))

,Customer_ID,Customer_Name,Gender,Age,City,Annual_Income,Purchase_Amount,Purchase_Date,Membership_Status,Payment_Method
0,CUST1019,Sneha Mishra,Female,59,Delhi,35949.00,657.15,2025-02-24,No,UPI
1,CUST1043,Pooja Sinha,Male,25,Kanpur,43284.00,11541.90,2025-05-07,Yes,UPI
2,CUST1037,Vikram Joshi,Female,52,Agra,46964.00,8468.17,2025-04-19,Yes,Cash
3,CUST1077,Rahul Yadav,Male,43,Delhi,79115.00,5935.62,2025-08-17,No,UPI
4,CUST1054,Vikram Joshi,Male,23,Delhi,59124.00,5926.93,2025-06-09,No,Credit Card
5,CUST1092,Neha Kapoor,Male,44,Delhi,71975.00,9626.28,2025-10-01,Yes,Credit Card
6,CUST1057,Rohan Verma,Female,39,Agra,92752.00,14235.10,2025-06-18,Yes,UPI
8,CUST1094,Priya Gupta,Male,44,Agra,68494.00,7090.85,2025-10-07,Yes,Debit Card
9,CUST1005,Aditya Jain,Female,43,Lucknow,110738.00,11757.99,2025-01-13,No,Debit Card
10,CUST1028,Ananya Singh,Female,57,Lucknow,35237.00,4751.56,2025-03-23,Yes,UPI

### Final Info

In [42]:
df.info()

<class 'pandas.DataFrame'>
Index: 114 entries, 0 to 124
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        114 non-null    string
 1   Customer_Name      114 non-null    string
 2   Gender             114 non-null    string
 3   Age                114 non-null    int64
 4   City               114 non-null    string
 5   Annual_Income      114 non-null    float64
 6   Purchase_Amount    114 non-null    float64
 7   Purchase_Date      114 non-null    datetime64[us]
 8   Membership_Status  114 non-null    string
 9   Payment_Method     114 non-null    string
dtypes: datetime64[us](1), float64(2), int64(1), string(6)
memory usage: 9.8 KB

### Final Quality Report

In [43]:
final_quality_report = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Null_Count": df.isnull().sum().values,
    "Unique_Values": df.nunique().values
})

final_quality_report

              Column       Data_Type  Null_Count  Unique_Values
0        Customer_ID          string           0            114
1      Customer_Name          string           0             15
2             Gender          string           0              2
3                Age           int64           0             38
4               City          string           0              6
5      Annual_Income         float64           0            110
6    Purchase_Amount         float64           0            111
7      Purchase_Date  datetime64[us]           0            114
8  Membership_Status          string           0              2
9     Payment_Method          string           0              4

## 15. **Exporting Cleaned Dataset**

The cleaned dataset is exported as a new CSV file.

The original messy dataset is preserved separately so that the cleaning process remains reproducible and auditable.

In [44]:
output_path = "../dataset/cleaned_customer_sales.csv"

df.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully.")
print("File:", output_path)

Cleaned dataset saved successfully.
File: ../dataset/cleaned_customer_sales.csv

## 16. **Conclusion**

The deliberately messy customer sales dataset was successfully transformed into an analysis-ready dataset.

### Key cleaning activities completed

- Identified missing values and selected appropriate treatment strategies
- Removed unusable records where essential information was unavailable
- Detected and removed duplicate records
- Standardised inconsistent categorical values
- Converted mixed date formats into datetime
- Corrected numerical data types
- Identified statistical outliers using the IQR method
- Applied logical range validation
- Corrected invalid age and purchase values
- Capped an extreme income value using the IQR upper bound
- Validated the cleaned dataset
- Compared data quality before and after cleaning
- Exported the cleaned dataset as a new CSV file

The resulting dataset is suitable for further exploratory data analysis and visualization.